// <auto-generated />
namespace BetterYouApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addbannedstatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addbannedstatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202407150139239_add banned status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
