version: '3.8'

services:
  betteryouapi:
    build:
      context: ./BetterYouApi
      dockerfile: DockerFile
    ports:
      - "5000:80"
    networks:
      - betteryou-network

  betteryouui:
    build:
      context: ./BetterYouUI
      dockerfile: DockerFile
    ports:
      - "3000:80"
    networks:
      - betteryou-network

networks:
  betteryou-network:
    driver: bridge
