import { Component } from '@angular/core';
import { FormBuilder, FormGroup, FormArray, Validators, ReactiveFormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { ButtonModule } from 'primeng/button';
import { CalendarModule } from 'primeng/calendar';
import { InputTextModule } from 'primeng/inputtext';
import { TableModule } from 'primeng/table';
import { MetricData } from '../../Models/Models';
import { MetricDataService } from '../../services/MetricDataService/MetricDataService';

@Component({
  selector: 'app-metrics',
  standalone: true,
  imports: [ CommonModule,
    ReactiveFormsModule,
    TableModule,
    ButtonModule,
    InputTextModule,
    CalendarModule],
  templateUrl: './metrics.component.html',
  styleUrl: './metrics.component.scss'
})
export class MetricsComponent {
  metricForm: FormGroup;
  entries: MetricData[] = [];

  constructor(private fb: FormBuilder, private dataService: MetricDataService) {
    this.metricForm = this.fb.group({
      weight: ['', Validators.required],
      reps: ['', Validators.required],
      date: ['', Validators.required]
    });
  }

  addEntry(): void {
    const newEntry: MetricData = {
      metricDataId: 0, // This would be generated by the backend
      userMetricId: 1, // Set appropriately
      dataValue: JSON.stringify({
        weight: this.metricForm.value.weight,
        reps: this.metricForm.value.reps
      }),
      dataDate: new Date(this.metricForm.value.date)
    };
    this.entries.push(newEntry);
    // sort the entries by date
    this.entries.sort((a, b) => a.dataDate.getTime() - b.dataDate.getTime());
    this.dataService.updateMetricData(this.entries);
    this.metricForm.reset();
  }

  removeEntry(index: number): void {
    this.entries.splice(index, 1);
    this.dataService.updateMetricData(this.entries);
  }

  onSubmit(): void {
    if (this.entries.length > 0) {
      console.log(this.entries);
      // Handle the form submission logic here
    }
  }
}
